### ISSUE TITLE
Pressing `Back` after a task/workflow form should not result in restart of the process

### ISSUE THREAD

**Issue by wouter1975** [workfloworchestrator/orchestrator-ui-library#1084]
Pressing `Back` should not result in visiting the new task/workflow page again. This could result in a unintentional rereun of a workflow which does not require any user input. Besides that it is quite unlogic/confusing to be presented the userform again.

- [ ] remove  the new form pages from the router stack

**Comment by Georgi2704** [comment]
https://github.com/workfloworchestrator/orchestrator-ui-library/pull/1145
https://git.ia.surfsara.nl/netdev/automation/projects/orchestrator-ui/-/merge_requests/122

Removing pages from the router stack is not possible, because the browser's history stack shows only the current url. I couldn't really find a way to get an array (stack) of all the pages since the start of the application.

What I tried is go around it, by skipping the page that contains `/new/workflow/ ` in the URL.

The first solution I tried was by saving the URL of the previous page when it's not `/new/workflow`. So pressing the back or forward button navigates us to the last page that is not the `/new/workflow` page. This way we lose the history, so only one back action is possible.

The second solution is without saving the previous page. I used router.back(). For example: If I press the back button on the browser and the previous page was `/new/workflow` page, it will redirect me to the page before it. So (-2 pages). I couldn't really make a solution for the forward button, because there aren't separate events for the forward and back buttons, thus we cannot differentiate between clicking forward or back. 

Some of the solutions I tried / docs:
https://liuzhenglai.com/post/5c3d01fae390632833f5774d
https://developer.mozilla.org/en-US/docs/Web/API/PopStateEvent/state

This one is deprecated:
https://developer.mozilla.org/en-US/docs/Web/API/Performance/navigation

If we don't want the **Create Workflow/Task** pages to not be Back/Forward navigated then isn't it by NextJS convention that they shouldn't really be pages ? Perhaps we should consider making them more modal-like.

@wouter1975 @DutchBen @ricardovdheijden
