### ISSUE TITLE
Investigate Approuter

### ISSUE THREAD

**Issue by DutchBen** [workfloworchestrator/orchestrator-ui-library#1510]
Consider the Approuter solution instead the pageRouter 
- [x] investigate first
- [ ] Create (optionally) extra tickets for the next steps

**Comment by ricardovdheijden** [comment]
Highlights of changes when moving to app router:
- Every page is a server page by default, can directly do server things in a component (environment variables, api calls, database queries)
- By default pages are cached, control with "export const dynamic = 'force-dynamic';" on page.tsx
  Can influense the caching behavior: see the difference between searchParams and params.
  There is also a way to pass extra config to fetch(), but this does not seem to be future proof (https://www.youtube.com/watch?v=VBlSe8tvg4U 14:30)
- router.refresh() --- invalidates cache, example: after changig display name in user profile
- router import: next/router --> next/navigation
- api route handlers: see https://www.youtube.com/watch?v=UlyoT08XBxM (~39:00 min)
- Calling api's on the server with dynamic data: import and call noStore() to disable this default cache https://www.youtube.com/watch?v=VBlSe8tvg4U (7:04min)

Redux:
- Will work with the app router: it runs only on the client
- Add "use-client" at the top of "packages/orchestrator-ui-components/src/rtk/storeProvider.tsx"

Considerations:
- Do we need to add "use-client" to all components with client-only logic that we export in the library? The assumption is that every exported component could be used any time anywhere by our consumers.
- Since we have RTK in place with its own caching we might not use fetch at server side, though it could work well for the components that populates fixed lists: New Subscription, New Task.
- Since every page is cached by default: how to prevent leaking data in cache to another user? Is it possible to accidently leak data by not configuring the cache well?
- How does this new app router and its new capabilities have effect on the redesign of the forms. Forms could be rendered on the server with all dropdowns filled (given dropdowns need api calls too)

Resources:
- https://nextjs.org/docs/pages/building-your-application/upgrading/app-router-migration#migrating-from-pages-to-app
- https://www.youtube.com/watch?v=YQMSietiFm0
- https://www.youtube.com/watch?v=UlyoT08XBxM
- https://www.youtube.com/watch?v=VBlSe8tvg4U
- https://www.youtube.com/watch?v=xfhQk9CRXbY

**Comment by ricardovdheijden** [comment]
An initial attempt to update our Surf specific app by adding the `app` folder wit a `layout.tsx` and `page.tsx` resulted in an error requiring both to be a client-component (adding `use-client`). This is in contrast with the documentation and indicates some more investigation is needed to actually get started with the migration to the app router.

As final note: the pages router does not seem to be deprecated any time soon (https://github.com/vercel/next.js/discussions/56655)

**Comment by Georgi2704** [comment]
I would say let's wait until React 19 and server components are released to production.
