### ISSUE TITLE
 Enhance WebSocket Connectivity with Reconnection Logic

### ISSUE THREAD

**Issue by tjeerddie** [workfloworchestrator/orchestrator-ui-library#822]
Currently, our application lacks reconnection logic for handling WebSocket disconnections. This enhancement aims to implement a robust reconnection mechanism, ensuring uninterrupted communication even in the event of a disconnection.

Introduce WebSocket reconnection logic with the following features:

1. **Maximum Reconnection Attempts:**
   - Allow the system to attempt reconnection a configurable number of times (denoted as 'x').
   - Define a reasonable default value and provide clear instructions on how to customize this value if needed.

2. **Incremental Reconnection Delays:**
   - Implement a strategy where the system waits progressively longer between reconnection attempts.
   - This helps avoid overwhelming the server with rapid reconnection requests in case of persistent connectivity issues.
   - Provide flexibility to configure the initial delay and the incremental factor, allowing users to fine-tune the reconnection timing based on their specific use cases.

**Comment by wouter1975** [comment]
First implement the manual reconnect ws

**Comment by ricardovdheijden** [comment]
Conclusions after investigating the disconnects of WS:

1) Frontend has a ping pong mechanism as heartbeat, it is set to 45 seconds. When the browser suspends the tab, the code on the page gets every 60 seconds time to execute. Therefore the logic in the frontend disconnects itself. -- removing the debounce code

2) Backend and environment has also timeouts set, these will be fixed by the backend team.

3) Current implementation is a manual way of implementing WS with heartbeat, in this branch is a POC to move to a react hook:
https://github.com/workfloworchestrator/orchestrator-ui-library/tree/822-websockets-reconnect
For the surf version of the app, see the `822-websockets-reconnect` branch

**Comment by Mark90** [comment]
> Frontend has a ping pong mechanism as heartbeat, it is set to 45 seconds. When the browser suspends the tab, the code on the page gets every 60 seconds time to execute. Therefore the logic in the frontend disconnects itself. -- removing the debounce code

As you and I found out today, sometimes the connection seems alive but is not _really_ alive. Probably this was the reason for the original debounce. That is another problem that we're looking into, but aside of that it might still be useful to keep track of the number of un-acked pings and then disconnect - so that the reconnection logic can kick in

**Comment by Mark90** [comment]
More on-topic;

> Maximum Reconnection Attempts:

I would not set a maximum, but just use exponential backoff (2^0 2^1 2^2 etc) and make the maximum backoff 2^8 seconds (a bit over 4 minutes) and after a successful connection reset it back to 2^0. The load this produces on the server is negligible.

**Comment by DutchBen** [comment]
Summary of meeting on this topics today:
- Having a mechanism like the debounce that shows the connection as disabled is desirable to avoid showing the status as active when it's actually not. 
- The way to solve the problem when the browser suspends is to do a reconnect when the page refocusses. RTK has an event for that. 
- The current code works. We'll keep it for now until there are additional reasons to move to the hook Ricardo found.
-
